SELECT 
   s.TABLE_NAME + ' -> ' + p.TABLE_NAME as 'Arrow'
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE s
ON s.CONSTRAINT_CATALOG    = rc.CONSTRAINT_CATALOG 
   AND s.CONSTRAINT_SCHEMA = rc.CONSTRAINT_SCHEMA
   AND s.CONSTRAINT_NAME   = rc.CONSTRAINT_NAME
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE p
ON p.CONSTRAINT_CATALOG = 
rc.UNIQUE_CONSTRAINT_CATALOG 
   AND p.CONSTRAINT_SCHEMA = rc.UNIQUE_CONSTRAINT_SCHEMA
   AND p.CONSTRAINT_NAME   = rc.UNIQUE_CONSTRAINT_NAME
   AND p.ORDINAL_POSITION  = s.ORDINAL_POSITION
;
